name: Deploy

on:
    push:
        branches: [ master ]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'

            -   uses: actions/checkout@v4

            #            -   uses: actions/setup-node@v4
            #                with:
            #                    node-version: 20
            #                    cache: 'npm'

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v4
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-

            -   name: Install Dependencies
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            #            - name: Build Frontend
            #              run: npm ci && ./node_modules/.bin/encore production

            -   name: upload
                uses: burnett01/rsync-deployments@5.2
                with:
                    switches: --exclude '.env.local' --exclude '.git' --exclude '.github' --exclude 'var' --exclude 'node_modules' -avzr --delete
                    path: ./
                    remote_path: /var/www/vhosts/bahuma.de/httpdocs/management
                    remote_host: server4.bahuma.io
                    remote_user: bahuma-me
                    remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

            -   name: executing post upload actions via ssh
                uses: appleboy/ssh-action@master
                with:
                    host: server4.bahuma.io
                    username: bahuma-me
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    port: 22
                    script: cd /var/www/vhosts/bahuma.de/httpdocs/management && /opt/plesk/php/8.3/bin/php bin/console cache:clear && /opt/plesk/php/8.3/bin/php bin/console doctrine:migrations:migrate && /opt/plesk/php/8.3/bin/php bin/console cache:clear && /opt/plesk/php/8.3/bin/php bin/console assets:install && /opt/plesk/php/8.3/bin/php bin/console importmap:install
